[client]
showDeploymentInfo = false
showErrorDetails = true

[logger]
level = "info"

[theme]
primaryColor = "#FF6E40"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
# Configuraci√≥n de seguridad
runOnSave = true
maxUploadSize = 100

# Carpeta para datos compartidos
# serverAddress = "localhost"
# serverPort = 8501
